language: python
cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - "pip install -e ."
  - "pip install pep8"
# command to run tests
script:
  # Tests
  - python setup.py test
  # pep8
  - pep8 .
  # Examples
  - (cd "samples/replicate-workbook" && python replicate_workbook.py)
  - (cd "samples/list-tds-info" && python list_tds_info.py)
  - (cd "samples/show-fields" && python show_fields.py)

