name: Publish to PyPi

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f  requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Package
      run: | 
        python setup.py sdist
        python setup.py bdist_wheel
        

  test-deploy:
  if: github.ref_type == 'tag' && contains(github.ref_name, 'test')
    needs: build
    environment:
      name: test-pypi
    runs-on: ubuntu-latest
    steps:
    - name: Publish 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/


  production-deploy:
    needs: build
    environment:
      name: pypi
    runs-on: ubuntu-latest
    steps:
    - name: Publish 📦 to Real PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://pypi.org/legacy/